In [27]:
# importing pandas module 
import pandas as pd 

# making data frame 
data = pd.read_csv("https://media.geeksforgeeks.org/wp-content/uploads/nba.csv", index_col='Name') 

# number of rows to return 
n = 9

# creating series 
series = data["Team"] 

# returning top n rows 
top = series.head(n = n) 

# display 
top 


Name
Avery Bradley    Boston Celtics
Jae Crowder      Boston Celtics
John Holland     Boston Celtics
R.J. Hunter      Boston Celtics
Jonas Jerebko    Boston Celtics
Amir Johnson     Boston Celtics
Jordan Mickey    Boston Celtics
Kelly Olynyk     Boston Celtics
Terry Rozier     Boston Celtics
Name: Team, dtype: object

In [3]:
top10 = series.head(10) 
top10

0    Avery Bradley
1      Jae Crowder
2     John Holland
3      R.J. Hunter
4    Jonas Jerebko
5     Amir Johnson
6    Jordan Mickey
7     Kelly Olynyk
8     Terry Rozier
9     Marcus Smart
Name: Name, dtype: object

In [4]:
# calling tail() method  
# storing in new variable 
data_bottom = data.tail() 
  
# display 
data_bottom

Name       Team  Number Position   Age Height  Weight College  \
453  Shelvin Mack  Utah Jazz     8.0       PG  26.0    6-3   203.0  Butler   
454     Raul Neto  Utah Jazz    25.0       PG  24.0    6-1   179.0     NaN   
455  Tibor Pleiss  Utah Jazz    21.0        C  26.0    7-3   256.0     NaN   
456   Jeff Withey  Utah Jazz    24.0        C  26.0    7-0   231.0  Kansas   
457           NaN        NaN     NaN      NaN   NaN    NaN     NaN     NaN   

        Salary  
453  2433333.0  
454   900000.0  
455  2900000.0  
456   947276.0  
457        NaN

In [5]:
# number of rows to return 
n = 12
  
# creating series 
series = data["Salary"] 
  
# returning top n rows 
bottom = series.tail(n = n) 
  
# display 
bottom

446    12000000.0
447     1175880.0
448    15409570.0
449     1348440.0
450     2050000.0
451      981348.0
452     2239800.0
453     2433333.0
454      900000.0
455     2900000.0
456      947276.0
457           NaN
Name: Salary, dtype: float64

In [6]:
data.describe()

Number         Age      Weight        Salary
count  457.000000  457.000000  457.000000  4.460000e+02
mean    17.678337   26.938731  221.522976  4.842684e+06
std     15.966090    4.404016   26.368343  5.229238e+06
min      0.000000   19.000000  161.000000  3.088800e+04
25%      5.000000   24.000000  200.000000  1.044792e+06
50%     13.000000   26.000000  220.000000  2.839073e+06
75%     25.000000   30.000000  240.000000  6.500000e+06
max     99.000000   40.000000  307.000000  2.500000e+07

In [7]:
# removing null values to avoid errors
data.dropna(inplace=True)
 
# percentile list
perc = [.20, .40, .60, .80]
 
# list of dtypes to include
include = ['object', 'float', 'int']
 
# calling describe method
desc = data.describe(percentiles=perc, include=include)
 
# display
desc

Name                  Team      Number Position         Age  \
count             364                   364  364.000000      364  364.000000   
unique            364                    30         NaN        5         NaN   
top     Avery Bradley  New Orleans Pelicans         NaN       SG         NaN   
freq                1                    16         NaN       87         NaN   
mean              NaN                   NaN   16.829670      NaN   26.615385   
std               NaN                   NaN   14.994162      NaN    4.233591   
min               NaN                   NaN    0.000000      NaN   19.000000   
20%               NaN                   NaN    4.000000      NaN   23.000000   
40%               NaN                   NaN    9.000000      NaN   25.000000   
50%               NaN                   NaN   12.000000      NaN   26.000000   
60%               NaN                   NaN   17.000000      NaN   27.000000   
80%               NaN                   NaN   30.000000      NaN   30.000000   
max               NaN                   NaN   99.000000      NaN   40.000000   

       Height      Weight   College        Salary  
count     364  364.000000       364  3.640000e+02  
unique     17         NaN       115           NaN  
top       6-9         NaN  Kentucky           NaN  
freq       49         NaN        22           NaN  
mean      NaN  219.785714       NaN  4.620311e+06  
std       NaN   24.793099       NaN  5.119716e+06  
min       NaN  161.000000       NaN  5.572200e+04  
20%       NaN  195.000000       NaN  9.472760e+05  
40%       NaN  212.000000       NaN  1.638754e+06  
50%       NaN  220.000000       NaN  2.515440e+06  
60%       NaN  228.000000       NaN  3.429934e+06  
80%       NaN  242.400000       NaN  7.838202e+06  
max       NaN  279.000000       NaN  2.287500e+07

In [8]:
# calling describe method
desc = data["Name"].describe()
 
# display
desc

count               364
unique              364
top       Avery Bradley
freq                  1
Name: Name, dtype: object

In [9]:
df = pd.DataFrame(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9],
     [10, 11, 12]],
    columns=['a', 'b', 'c'])
arr=df.to_numpy()
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int64)

In [10]:
arr=df[['a','c']].to_numpy()
arr

array([[ 1,  3],
       [ 4,  6],
       [ 7,  9],
       [10, 12]], dtype=int64)

In [11]:
arr.dtype

dtype('int64')

In [12]:
# creating DataFrame from weight column
df = pd.DataFrame(data['Weight'].head())
 
# using to_numpy() function
print(df.to_numpy())

[[180.]
 [235.]
 [185.]
 [235.]
 [238.]]


In [13]:
print(df.to_numpy(dtype='float32'))

[[180.]
 [235.]
 [185.]
 [235.]
 [238.]]


In [14]:
type(df.to_numpy())

numpy.ndarray

In [16]:
# creating series form weight column 
gfg = pd.Series(data['Weight'].head()) 
  
# using to_numpy() function 
print(type(gfg.to_numpy()))
print(gfg.to_numpy())

<class 'numpy.ndarray'>
[180. 235. 185. 235. 238.]


In [17]:
# Creating the Series 
sr = pd.Series(['New York', 'Chicago', 'Toronto', 'Lisbon', 'Rio']) 
  
# Create the Index 
index_ = ['City 1', 'City 2', 'City 3', 'City 4', 'City 5']  
  
# set the index 
sr.index = index_ 
  
# Print the series 
print(sr) 

City 1    New York
City 2     Chicago
City 3     Toronto
City 4      Lisbon
City 5         Rio
dtype: object


In [19]:
# return numpy array representation 
result = sr.as_matrix()
  
# Print the result 
print(result) 

AttributeError: 'Series' object has no attribute 'as_matrix'

In [21]:
# making data frame 
df = pd.read_csv('nba.csv') 

new_row = pd.DataFrame({'Name':'Geeks', 'Team':'Boston', 'Number':3,
                        'Position':'PG', 'Age':33, 'Height':'6-2',
                        'Weight':189, 'College':'MIT', 'Salary':99999},
                         index =[0])
# simply concatenate both dataframes
df = pd.concat([new_row, df]).reset_index(drop = True)
df.head(5)

Name            Team  Number Position   Age Height  Weight  \
0          Geeks          Boston     3.0       PG  33.0    6-2   189.0   
1  Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
2    Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
3   John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   
4    R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   

             College     Salary  
0                MIT    99999.0  
1              Texas  7730337.0  
2          Marquette  6796117.0  
3  Boston University        NaN  
4      Georgia State  1148640.0

In [30]:
# dropping passed values
data.drop(["Avery Bradley", "John Holland", "R.J. Hunter",
                            "R.J. Hunter"], inplace = True)
 
# display
data

Team  Number Position   Age Height  Weight  \
Name                                                                  
Jae Crowder    Boston Celtics    99.0       SF  25.0    6-6   235.0   
Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   
Amir Johnson   Boston Celtics    90.0       PF  29.0    6-9   240.0   
Jordan Mickey  Boston Celtics    55.0       PF  21.0    6-8   235.0   
Kelly Olynyk   Boston Celtics    41.0        C  25.0    7-0   238.0   
...                       ...     ...      ...   ...    ...     ...   
Shelvin Mack        Utah Jazz     8.0       PG  26.0    6-3   203.0   
Raul Neto           Utah Jazz    25.0       PG  24.0    6-1   179.0   
Tibor Pleiss        Utah Jazz    21.0        C  26.0    7-3   256.0   
Jeff Withey         Utah Jazz    24.0        C  26.0    7-0   231.0   
NaN                       NaN     NaN      NaN   NaN    NaN     NaN   

                 College      Salary  
Name                                  
Jae Crowder    Marquette   6796117.0  
Jonas Jerebko        NaN   5000000.0  
Amir Johnson         NaN  12000000.0  
Jordan Mickey        LSU   1170960.0  
Kelly Olynyk     Gonzaga   2165160.0  
...                  ...         ...  
Shelvin Mack      Butler   2433333.0  
Raul Neto            NaN    900000.0  
Tibor Pleiss         NaN   2900000.0  
Jeff Withey       Kansas    947276.0  
NaN                  NaN         NaN  

[455 rows x 8 columns]

In [31]:
# importing pandas package 
import pandas as pd 

# making data frame from csv file 
data = pd.read_csv("nba.csv", index_col ="Name") 

# retrieving rows by loc method 
rows = data.loc[["Avery Bradley", "R.J. Hunter"]] 

# checking data type of rows 
print(type(rows)) 

# display 
rows 


<class 'pandas.core.frame.DataFrame'>


Team  Number Position   Age Height  Weight  \
Name                                                                  
Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
R.J. Hunter    Boston Celtics    28.0       SG  22.0    6-5   185.0   

                     College     Salary  
Name                                     
Avery Bradley          Texas  7730337.0  
R.J. Hunter    Georgia State  1148640.0

In [32]:
# importing pandas package 
import pandas as pd 

# making data frame from csv file 
data = pd.read_csv("nba.csv", index_col ="Team") 

# retrieving rows by loc method 
rows = data.loc["Utah Jazz"] 

# checking data type of rows 
print(type(rows)) 

# display 
rows 


<class 'pandas.core.frame.DataFrame'>


Name  Number Position   Age Height  Weight       College  \
Team                                                                            
Utah Jazz   Trevor Booker    33.0       PF  28.0    6-8   228.0       Clemson   
Utah Jazz      Trey Burke     3.0       PG  23.0    6-1   191.0      Michigan   
Utah Jazz      Alec Burks    10.0       SG  24.0    6-6   214.0      Colorado   
Utah Jazz      Dante Exum    11.0       PG  20.0    6-6   190.0           NaN   
Utah Jazz  Derrick Favors    15.0       PF  24.0   6-10   265.0  Georgia Tech   
Utah Jazz     Rudy Gobert    27.0        C  23.0    7-1   245.0           NaN   
Utah Jazz  Gordon Hayward    20.0       SF  26.0    6-8   226.0        Butler   
Utah Jazz     Rodney Hood     5.0       SG  23.0    6-8   206.0          Duke   
Utah Jazz      Joe Ingles     2.0       SF  28.0    6-8   226.0           NaN   
Utah Jazz   Chris Johnson    23.0       SF  26.0    6-6   206.0        Dayton   
Utah Jazz      Trey Lyles    41.0       PF  20.0   6-10   234.0      Kentucky   
Utah Jazz    Shelvin Mack     8.0       PG  26.0    6-3   203.0        Butler   
Utah Jazz       Raul Neto    25.0       PG  24.0    6-1   179.0           NaN   
Utah Jazz    Tibor Pleiss    21.0        C  26.0    7-3   256.0           NaN   
Utah Jazz     Jeff Withey    24.0        C  26.0    7-0   231.0        Kansas   

               Salary  
Team                   
Utah Jazz   4775000.0  
Utah Jazz   2658240.0  
Utah Jazz   9463484.0  
Utah Jazz   3777720.0  
Utah Jazz  12000000.0  
Utah Jazz   1175880.0  
Utah Jazz  15409570.0  
Utah Jazz   1348440.0  
Utah Jazz   2050000.0  
Utah Jazz    981348.0  
Utah Jazz   2239800.0  
Utah Jazz   2433333.0  
Utah Jazz    900000.0  
Utah Jazz   2900000.0  
Utah Jazz    947276.0

In [33]:
# importing pandas package
import pandas as pd

# making data frame from csv file
data = pd.read_csv('nba.csv')

# retrieving rows by loc method
row1 = data.loc[3]

# retrieving rows by iloc method
row2 = data.iloc[3]

# checking if values are equal
row1 == row2


Name        True
Team        True
Number      True
Position    True
Age         True
Height      True
Weight      True
College     True
Salary      True
Name: 3, dtype: bool

In [34]:
# retrieving rows by loc method
row1 = data.iloc[[4, 5, 6, 7]]
 
# retrieving rows by loc method
row2 = data.iloc[4:8]
 
# comparing values
row1 == row2

Name  Team  Number  Position   Age  Height  Weight  College  Salary
4  True  True    True      True  True    True    True    False    True
5  True  True    True      True  True    True    True    False    True
6  True  True    True      True  True    True    True     True    True
7  True  True    True      True  True    True    True     True    True

In [35]:
# Extracting a single row by index
row_alice = data.iloc[0, :]
print("\nExtracted Row (Geek1):")
print(row_alice)
 
# Extracting multiple rows using a slice
rows_geek2_to_geek3 = data.iloc[1:3, :]
print("\nExtracted Rows (Geek2 to Geek3):")
print(rows_geek2_to_geek3)


Extracted Row (Geek1):
Name         Avery Bradley
Team        Boston Celtics
Number                 0.0
Position                PG
Age                   25.0
Height                 6-2
Weight               180.0
College              Texas
Salary           7730337.0
Name: 0, dtype: object

Extracted Rows (Geek2 to Geek3):
           Name            Team  Number Position   Age Height  Weight  \
1   Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
2  John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   

             College     Salary  
1          Marquette  6796117.0  
2  Boston University        NaN  
